### ISSUE TITLE
grantlee5 deployed without plugin libraries

### ISSUE THREAD

**Issue by dragotin** [TheAssassin/appimagecraft#15]
My project Kraft is building with appimagecraft: https://github.com/dragotin/kraft

It uses the grantlee templating library, which unfortunately does not work because it does not find it's plugin libraries that it seems to include on runtime.

The plugins are part of the main package `grantlee5` (in my case):
```
/usr/lib64/grantlee/5.2
/usr/lib64/grantlee/5.2/grantlee_defaultfilters.so
/usr/lib64/grantlee/5.2/grantlee_defaulttags.so
/usr/lib64/grantlee/5.2/grantlee_i18ntags.so
/usr/lib64/grantlee/5.2/grantlee_loadertags.so
```
The grantlee package also provides a "main" lib called /usr/lib64/libGrantlee_TextDocument.so.5 that is not copied to the AppImage, while the other one ends up in  usr/lib/libGrantlee_Templates.so.5 in the AppImage. I wonder if libGrantlee_TextDocument shoudn't be copied over as well?

How can this be fixed?  Thanks!

**Comment by TheAssassin** [comment]
I think the easiest way to automate copying these would be to create a dedicated linuxdeploy plugin. linuxdeploy-plugin-qt copies such `dlopen`ed libraries all the time, too. The question is, how can we tell `libgrantlee` to load these?

**Comment by TheAssassin** [comment]
Looks like we just need to copy these files into the Qt plugin dir. linuxdeploy-plugin-qt already sets up such a directory and a matching `qt.conf`. I guess when using a suitable linuxdeploy plugin in combination with the Qt plugin, everything should be good.

**Comment by dragotin** [comment]
Hmm, I fear I still dont know how to fix this in my case...

**Comment by TheAssassin** [comment]
Just add `- https://github.com/linuxdeploy/misc-plugins/raw/master/grantlee5/linuxdeploy-plugin-grantlee5.sh` to the plugins in your `appimagecraft.yml`. Tested, works.

The plugin can be found in https://github.com/linuxdeploy/misc-plugins/tree/master/grantlee5.

**Comment by dragotin** [comment]
I tried to figure the correct line to add it, but failed. Non of my attempts were right. 

Would you mind to paste the change here?

For reference: https://github.com/dragotin/kraft/blob/appimage-grantlee/appimagecraft.yml

**Comment by TheAssassin** [comment]
I suppose the build system's CMake is too old and doesn't properly support the "auto-guess" feature I built into that plugin, looking at the log. Not entirely sure why. Adding a line like `GRANTLEE5_PLUGINS_DIR: /usr/lib/x86_64-linux-gnu/grantlee5/5.1/` (obviously needs to match the actual container) to linuxdeploy's environment should fix the problem.

Edit: apparently, the path is `/usr/lib64/grantlee/5.2/` on openSUSE Leap 15.2.

**Comment by TheAssassin** [comment]
Fix provided in https://github.com/linuxdeploy/misc-plugins/commit/1135557d0fd1298a5d8309b182fc3c0bdca75000, autodetection appears to work on Leap 15.2 now. Testing this a bit more.

The fix provided in my previous comment however works perfectly fine. See https://github.com/TheAssassin/kraft/actions/runs/3123960384/jobs/5066945154.

**Comment by TheAssassin** [comment]
Fixed the autodetection bug.

**Comment by dragotin** [comment]
Have you ever tried to run the AppImage that resulted from your build above and use the Grantlee?

I still get this when running my AppImage:
```
grantlee.template: "Plugin library 'grantlee_defaulttags' not found."
Grantlee template load failed: "Plugin library 'grantlee_defaulttags' not found."
```
built from 
https://github.com/dragotin/kraft/blob/checkAppImage/appimagecraft.yml

**Comment by TheAssassin** [comment]
It seemed to work just fine, but since I have no real idea of your application, I guess I haven't tried it well enough. Please open an issue over at https://github.com/linuxdeploy/misc-plugins, describing how I can easily reproduce these lines.

**Comment by TheAssassin** [comment]
Should be fixed now.
